In [1]:
import pandas as pd
import numpy as np

In [2]:
survey_data = pd.read_csv("./data/data_individual_clean.csv")

In [3]:
survey_data

,share_sm,age,gender,education_level,income_level,cond,ResponseId,country,finished,condName,belief_in_cc,policy_support,wept,country_standard,alpha2,alpha3
0,1.0,35.0,2.0,3.0,5.0,5,R_1r7Yr7R1xMimIvj,usa,1,CollectAction,88.50,89.000000,1.0,United States,US,USA
1,0.0,39.0,1.0,3.0,4.0,1,R_2ATgV5VxewrTRiI,usa,1,Control,50.25,66.222222,0.0,United States,US,USA
2,1.0,55.0,1.0,3.0,5.0,9,R_3ENlePBlLyYjExr,usa,1,Letter2Future,84.00,84.222222,1.0,United States,US,USA
3,0.0,66.0,1.0,3.0,5.0,4,R_2c0HQgvYzas6mus,usa,1,SciConsens,0.50,1.222222,0.0,United States,US,USA
4,0.0,53.0,2.0,3.0,5.0,8,R_00siryCwgdMus6J,usa,1,PluralIgnorance,57.50,80.222222,0.0,United States,US,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59503,0.0,24.0,4.0,3.0,2.0,11,R_2TuXye2HP6EO5KZ,vietnam,1,FutureSelfCont,80.75,82.500000,0.0,Viet Nam,VN,VNM
59504,1.0,19.0,1.0,3.0,2.0,12,R_3R3p8C0gzLKTcCu,vietnam,1,BindingMoral,96.50,86.444444,0.0,Viet Nam,VN,VNM
59505,1.0,28.0,4.0,3.0,1.0,8,R_OeT1JV3yC1aJ4EF,vietnam,1,PluralIgnorance,100.00,83.333333,7.0,Viet Nam,VN,VNM
59506,1.0,20.0,1.0,3.0,9.0,3,R_2azVf0KXD3rtly8,vietnam,1,NegativeEmotions,64.75,66.666667,8.0,Viet Nam,VN,VNM
59507,1.0,18.0,2.0,3.0,5.0,1,R_3j0DcbTReKZgR9O,vietnam,1,Control,100.00,62.000000,8.0,Viet Nam,VN,VNM

In [4]:
survey_data.loc[survey_data["share_sm"] > 1, "share_sm"] = None
np.sum(survey_data["share_sm"].isna())

np.int64(15415)

In [5]:
survey_data.loc[:, "share_sm_jittered"] = survey_data["share_sm"] + np.random.normal(0, 0.15, size=survey_data.shape[0])
survey_data

,share_sm,age,gender,education_level,income_level,cond,ResponseId,country,finished,condName,belief_in_cc,policy_support,wept,country_standard,alpha2,alpha3,share_sm_jittered
0,1.0,35.0,2.0,3.0,5.0,5,R_1r7Yr7R1xMimIvj,usa,1,CollectAction,88.50,89.000000,1.0,United States,US,USA,0.931067
1,0.0,39.0,1.0,3.0,4.0,1,R_2ATgV5VxewrTRiI,usa,1,Control,50.25,66.222222,0.0,United States,US,USA,-0.011967
2,1.0,55.0,1.0,3.0,5.0,9,R_3ENlePBlLyYjExr,usa,1,Letter2Future,84.00,84.222222,1.0,United States,US,USA,0.885251
3,0.0,66.0,1.0,3.0,5.0,4,R_2c0HQgvYzas6mus,usa,1,SciConsens,0.50,1.222222,0.0,United States,US,USA,0.202750
4,0.0,53.0,2.0,3.0,5.0,8,R_00siryCwgdMus6J,usa,1,PluralIgnorance,57.50,80.222222,0.0,United States,US,USA,0.157781
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59503,0.0,24.0,4.0,3.0,2.0,11,R_2TuXye2HP6EO5KZ,vietnam,1,FutureSelfCont,80.75,82.500000,0.0,Viet Nam,VN,VNM,0.083595
59504,1.0,19.0,1.0,3.0,2.0,12,R_3R3p8C0gzLKTcCu,vietnam,1,BindingMoral,96.50,86.444444,0.0,Viet Nam,VN,VNM,0.917701
59505,1.0,28.0,4.0,3.0,1.0,8,R_OeT1JV3yC1aJ4EF,vietnam,1,PluralIgnorance,100.00,83.333333,7.0,Viet Nam,VN,VNM,0.809204
59506,1.0,20.0,1.0,3.0,9.0,3,R_2azVf0KXD3rtly8,vietnam,1,NegativeEmotions,64.75,66.666667,8.0,Viet Nam,VN,VNM,0.889610
59507,1.0,18.0,2.0,3.0,5.0,1,R_3j0DcbTReKZgR9O,vietnam,1,Control,100.00,62.000000,8.0,Viet Nam,VN,VNM,0.981393

In [6]:
survey_data.to_csv("./data/data_individual_clean2.csv", index=False)

In [7]:
# function to calculate entropy for binary variables
def calculate_entropy(series):
    """Calculate the entropy of a binary pandas Series."""
    p = series.mean()
    if p == 0 or p == 1:
        return 0
    return -p * np.log2(p) - (1 - p) * np.log2(1 - p)

In [8]:
ctr_aggregates = survey_data.groupby('alpha3').agg(
    belief_cc_mean =('belief_in_cc', 'mean'),
    belief_cc_std = ('belief_in_cc', 'std'),
    policy_support_mean = ('policy_support', 'mean'),
    policy_support_std = ('policy_support', 'std'),
    wept_mean = ('wept', 'mean'),
    wept_std = ('wept', 'std'),
    share_social_media_mean = ('share_sm', 'mean'),
    share_social_media_entropy = ('share_sm', calculate_entropy)
)

In [9]:
ctr_aggregates

,belief_cc_mean,belief_cc_std,policy_support_mean,policy_support_std,wept_mean,wept_std,share_social_media_mean,share_social_media_entropy
alpha3,,,,,,,,
ARE,77.109855,22.060179,69.156442,18.390162,5.828520,3.141252,0.820202,0.679635
ARM,84.572959,18.674765,69.761351,17.028982,3.428862,3.339119,0.324100,0.908784
AUS,76.194700,25.622779,70.068518,19.983359,5.500511,3.353225,0.448718,0.992399
AUT,76.328000,24.614908,66.689438,20.065714,3.886454,3.516295,0.266476,0.836362
BEL,74.775921,23.724149,65.795834,18.573789,5.030482,3.465814,0.341360,0.926114
...,...,...,...,...,...,...,...,...
URY,87.555835,17.238309,76.725931,15.240031,5.000000,3.398292,0.676966,0.907650
USA,70.621961,29.677161,65.449652,24.126171,4.785775,3.518755,0.604696,0.968137
VEN,84.206818,25.277516,77.401237,19.967945,5.900000,3.019660,0.666667,0.918296
VNM,87.710183,16.250127,75.955019,17.121254,4.597911,3.382306,0.800604,0.720718
ZAF,84.511593,20.545773,72.849170,18.278096,4.772177,3.506201,0.770936,0.776376

In [10]:
def normalize_zero_hundred(series):
    """Normalize a pandas Series to a 0-100 scale."""
    min_val = series.min()
    max_val = series.max()
    return 100 * (series - min_val) / (max_val - min_val)

In [11]:
for col in ctr_aggregates.columns:
    ctr_aggregates[col] = normalize_zero_hundred(ctr_aggregates[col])

In [12]:
ctr_aggregates

,belief_cc_mean,belief_cc_std,policy_support_mean,policy_support_std,wept_mean,wept_std,share_social_media_mean,share_social_media_entropy
alpha3,,,,,,,,
ARE,32.177817,62.095841,47.262554,61.991618,94.856919,66.290545,85.153938,50.757058
ARM,59.977744,46.720300,49.948398,52.972068,46.499918,81.412989,20.594619,86.011720
AUS,28.768881,78.276105,51.312243,72.548581,88.247004,82.491110,36.811572,98.875804
AUT,29.265420,73.698655,36.308865,73.094292,55.721147,94.954083,13.095820,74.869528
BEL,23.483953,69.653091,32.341194,63.208380,78.775159,91.095965,22.840722,88.677916
...,...,...,...,...,...,...,...,...
URY,71.088902,40.196348,80.871670,41.117982,78.160901,85.935425,66.514232,85.837236
USA,8.010528,96.689894,30.804119,100.000000,73.843917,95.142110,57.109522,95.143171
VEN,58.613875,76.708022,83.870082,72.446444,96.297360,56.997556,65.173910,87.475093
VNM,71.663845,35.708321,77.448762,53.583483,70.058160,84.713690,82.603617,57.077700
ZAF,59.749155,55.217859,63.658550,61.249038,73.569907,94.182672,78.742794,65.640719

In [13]:
ctr_aggregates = ctr_aggregates.reset_index()

In [14]:
ctr_data = pd.read_csv("./data/data_country_clean.csv")
ctr_data

,Unnamed: 0,country,belief_in_cc_mean,policy_support_mean,share_sm_rate,mean_wept,best_intv_bcc,best_intv_policy,best_intv_share,best_intv_wept
0,0,algeria,79.86,75.22,71.72,55.56,Identity-Social-Norms-Intervention,CollectAction,FutureSelfCont,Control
1,1,armenia,84.57,69.76,32.41,42.86,Letter2Future,Letter2Future,Identity-Social-Norms-Intervention,FutureSelfCont
2,2,australia,76.19,70.07,44.87,68.76,PsychDistance,PsychDistance,SystemJust,PluralIgnorance
3,3,austria,76.33,66.69,26.65,48.58,SciConsens,DynamicNorm,DynamicNorm,PsychDistance
4,4,belgium,74.78,65.80,34.14,62.88,PluralIgnorance,FutureSelfCont,CollectAction,DynamicNorm
...,...,...,...,...,...,...,...,...,...,...
58,58,unitedarabemirates,77.11,69.16,82.02,72.86,CollectAction,CollectAction,BindingMoral,NegativeEmotions
59,59,uruguay,87.56,76.73,67.70,62.50,FutureSelfCont,FutureSelfCont,NegativeEmotions,FutureSelfCont
60,60,usa,70.62,65.45,60.47,59.82,PsychDistance,Letter2Future,Letter2Future,DynamicNorm
61,61,venezuela,84.21,77.40,66.67,73.75,BindingMoral,FutureSelfCont,Letter2Future,SystemJust
62,62,vietnam,87.71,75.96,80.06,57.47,FutureSelfCont,FutureSelfCont,CollectAction,Control

In [15]:
ctr_standard = survey_data[["alpha2", "alpha3", "country_standard", "country"]].groupby("alpha3").first()
ctr_standard = ctr_standard.reset_index()

In [16]:
ctr_standard

   alpha3 alpha2                   country_standard             country
0     ARE     AE               United Arab Emirates  unitedarabemirates
1     ARM     AM                            Armenia             armenia
2     AUS     AU                          Australia           australia
3     AUT     AT                            Austria             austria
4     BEL     BE                            Belgium             belgium
..    ...    ...                                ...                 ...
58    URY     UY                            Uruguay             uruguay
59    USA     US                      United States                 usa
60    VEN     VE  Venezuela, Bolivarian Republic of           venezuela
61    VNM     VN                           Viet Nam             vietnam
62    ZAF     ZA                       South Africa         southafrica

[63 rows x 4 columns]

In [17]:
ctr_w_names = ctr_aggregates.merge(ctr_standard, on = "alpha3", how = "left")

In [18]:
ctr_w_names

,alpha3,belief_cc_mean,belief_cc_std,policy_support_mean,policy_support_std,wept_mean,wept_std,share_social_media_mean,share_social_media_entropy,alpha2,country_standard,country
0,ARE,32.177817,62.095841,47.262554,61.991618,94.856919,66.290545,85.153938,50.757058,AE,United Arab Emirates,unitedarabemirates
1,ARM,59.977744,46.720300,49.948398,52.972068,46.499918,81.412989,20.594619,86.011720,AM,Armenia,armenia
2,AUS,28.768881,78.276105,51.312243,72.548581,88.247004,82.491110,36.811572,98.875804,AU,Australia,australia
3,AUT,29.265420,73.698655,36.308865,73.094292,55.721147,94.954083,13.095820,74.869528,AT,Austria,austria
4,BEL,23.483953,69.653091,32.341194,63.208380,78.775159,91.095965,22.840722,88.677916,BE,Belgium,belgium
...,...,...,...,...,...,...,...,...,...,...,...,...
58,URY,71.088902,40.196348,80.871670,41.117982,78.160901,85.935425,66.514232,85.837236,UY,Uruguay,uruguay
59,USA,8.010528,96.689894,30.804119,100.000000,73.843917,95.142110,57.109522,95.143171,US,United States,usa
60,VEN,58.613875,76.708022,83.870082,72.446444,96.297360,56.997556,65.173910,87.475093,VE,"Venezuela, Bolivarian Republic of",venezuela
61,VNM,71.663845,35.708321,77.448762,53.583483,70.058160,84.713690,82.603617,57.077700,VN,Viet Nam,vietnam
62,ZAF,59.749155,55.217859,63.658550,61.249038,73.569907,94.182672,78.742794,65.640719,ZA,South Africa,southafrica

In [19]:
ctr_data_ex = pd.read_csv("./data/data_country_clean.csv")
ctr_data_ex

,Unnamed: 0,country,belief_in_cc_mean,policy_support_mean,share_sm_rate,mean_wept,best_intv_bcc,best_intv_policy,best_intv_share,best_intv_wept
0,0,algeria,79.86,75.22,71.72,55.56,Identity-Social-Norms-Intervention,CollectAction,FutureSelfCont,Control
1,1,armenia,84.57,69.76,32.41,42.86,Letter2Future,Letter2Future,Identity-Social-Norms-Intervention,FutureSelfCont
2,2,australia,76.19,70.07,44.87,68.76,PsychDistance,PsychDistance,SystemJust,PluralIgnorance
3,3,austria,76.33,66.69,26.65,48.58,SciConsens,DynamicNorm,DynamicNorm,PsychDistance
4,4,belgium,74.78,65.80,34.14,62.88,PluralIgnorance,FutureSelfCont,CollectAction,DynamicNorm
...,...,...,...,...,...,...,...,...,...,...
58,58,unitedarabemirates,77.11,69.16,82.02,72.86,CollectAction,CollectAction,BindingMoral,NegativeEmotions
59,59,uruguay,87.56,76.73,67.70,62.50,FutureSelfCont,FutureSelfCont,NegativeEmotions,FutureSelfCont
60,60,usa,70.62,65.45,60.47,59.82,PsychDistance,Letter2Future,Letter2Future,DynamicNorm
61,61,venezuela,84.21,77.40,66.67,73.75,BindingMoral,FutureSelfCont,Letter2Future,SystemJust
62,62,vietnam,87.71,75.96,80.06,57.47,FutureSelfCont,FutureSelfCont,CollectAction,Control

In [20]:
ctr_merged = ctr_w_names.merge(ctr_data_ex[["best_intv_bcc", "best_intv_policy", "best_intv_share", "best_intv_wept", "country"]], on = "country", how = "left")

In [21]:
ctr_merged

,alpha3,belief_cc_mean,belief_cc_std,policy_support_mean,policy_support_std,wept_mean,wept_std,share_social_media_mean,share_social_media_entropy,alpha2,country_standard,country,best_intv_bcc,best_intv_policy,best_intv_share,best_intv_wept
0,ARE,32.177817,62.095841,47.262554,61.991618,94.856919,66.290545,85.153938,50.757058,AE,United Arab Emirates,unitedarabemirates,CollectAction,CollectAction,BindingMoral,NegativeEmotions
1,ARM,59.977744,46.720300,49.948398,52.972068,46.499918,81.412989,20.594619,86.011720,AM,Armenia,armenia,Letter2Future,Letter2Future,Identity-Social-Norms-Intervention,FutureSelfCont
2,AUS,28.768881,78.276105,51.312243,72.548581,88.247004,82.491110,36.811572,98.875804,AU,Australia,australia,PsychDistance,PsychDistance,SystemJust,PluralIgnorance
3,AUT,29.265420,73.698655,36.308865,73.094292,55.721147,94.954083,13.095820,74.869528,AT,Austria,austria,SciConsens,DynamicNorm,DynamicNorm,PsychDistance
4,BEL,23.483953,69.653091,32.341194,63.208380,78.775159,91.095965,22.840722,88.677916,BE,Belgium,belgium,PluralIgnorance,FutureSelfCont,CollectAction,DynamicNorm
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,URY,71.088902,40.196348,80.871670,41.117982,78.160901,85.935425,66.514232,85.837236,UY,Uruguay,uruguay,FutureSelfCont,FutureSelfCont,NegativeEmotions,FutureSelfCont
59,USA,8.010528,96.689894,30.804119,100.000000,73.843917,95.142110,57.109522,95.143171,US,United States,usa,PsychDistance,Letter2Future,Letter2Future,DynamicNorm
60,VEN,58.613875,76.708022,83.870082,72.446444,96.297360,56.997556,65.173910,87.475093,VE,"Venezuela, Bolivarian Republic of",venezuela,BindingMoral,FutureSelfCont,Letter2Future,SystemJust
61,VNM,71.663845,35.708321,77.448762,53.583483,70.058160,84.713690,82.603617,57.077700,VN,Viet Nam,vietnam,FutureSelfCont,FutureSelfCont,CollectAction,Control
62,ZAF,59.749155,55.217859,63.658550,61.249038,73.569907,94.182672,78.742794,65.640719,ZA,South Africa,southafrica,CollectAction,CollectAction,CollectAction,SciConsens

In [25]:
for col in ctr_merged.columns[1:9]:
    ctr_merged[col + "_rank"] = ctr_merged[col].rank(method="min", ascending=False)

In [26]:
ctr_merged

,alpha3,belief_cc_mean,belief_cc_std,policy_support_mean,policy_support_std,wept_mean,wept_std,share_social_media_mean,share_social_media_entropy,alpha2,...,best_intv_share,best_intv_wept,belief_cc_mean_rank,belief_cc_std_rank,policy_support_mean_rank,policy_support_std_rank,wept_mean_rank,wept_std_rank,share_social_media_mean_rank,share_social_media_entropy_rank
0,ARE,32.177817,62.095841,47.262554,61.991618,94.856919,66.290545,85.153938,50.757058,AE,...,BindingMoral,NegativeEmotions,43.0,29.0,43.0,25.0,5.0,55.0,10.0,52.0
1,ARM,59.977744,46.720300,49.948398,52.972068,46.499918,81.412989,20.594619,86.011720,AM,...,Identity-Social-Norms-Intervention,FutureSelfCont,23.0,42.0,40.0,41.0,60.0,40.0,50.0,26.0
2,AUS,28.768881,78.276105,51.312243,72.548581,88.247004,82.491110,36.811572,98.875804,AU,...,SystemJust,PluralIgnorance,48.0,8.0,39.0,12.0,14.0,37.0,41.0,7.0
3,AUT,29.265420,73.698655,36.308865,73.094292,55.721147,94.954083,13.095820,74.869528,AT,...,DynamicNorm,PsychDistance,47.0,16.0,51.0,10.0,54.0,7.0,54.0,34.0
4,BEL,23.483953,69.653091,32.341194,63.208380,78.775159,91.095965,22.840722,88.677916,BE,...,CollectAction,DynamicNorm,55.0,20.0,53.0,24.0,24.0,14.0,47.0,20.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,URY,71.088902,40.196348,80.871670,41.117982,78.160901,85.935425,66.514232,85.837236,UY,...,NegativeEmotions,FutureSelfCont,13.0,49.0,12.0,57.0,27.0,27.0,24.0,27.0
59,USA,8.010528,96.689894,30.804119,100.000000,73.843917,95.142110,57.109522,95.143171,US,...,Letter2Future,DynamicNorm,60.0,2.0,55.0,1.0,34.0,6.0,33.0,9.0
60,VEN,58.613875,76.708022,83.870082,72.446444,96.297360,56.997556,65.173910,87.475093,VE,...,Letter2Future,SystemJust,26.0,13.0,9.0,13.0,4.0,61.0,26.0,22.0
61,VNM,71.663845,35.708321,77.448762,53.583483,70.058160,84.713690,82.603617,57.077700,VN,...,CollectAction,Control,11.0,52.0,16.0,39.0,39.0,29.0,14.0,45.0
62,ZAF,59.749155,55.217859,63.658550,61.249038,73.569907,94.182672,78.742794,65.640719,ZA,...,CollectAction,SciConsens,24.0,35.0,27.0,27.0,35.0,9.0,19.0,40.0

In [27]:
ctr_merged.to_csv("./data/data_country_final.csv", index=False)